# This file was generated by GoReleaser. DO NOT EDIT.
class Gmcat < Formula
  desc "GmCat is a tool to interact with The GreyMatter Service Mesh's Catalog"
  homepage "https://github.com/greymatter-io/gmcat"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greymatter-io/gmcat/releases/download/v0.0.5/gmcat_0.0.5_darwin_amd64.tar.gz"
    sha256 "2df524b9a027225cc4a5f4ff11408d3baab85355af6f488cdaf3be83513b6601"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/greymatter-io/gmcat/releases/download/v0.0.5/gmcat_0.0.5_linux_amd64.tar.gz"
      sha256 "6f3dd427d5969e6e8247eb62cedfd32b12ec1e4a865c01a173c12b5f5a9f84b6"
    end
  end

  def install
    bin.install "gmcat"
  end

  test do
    system "#{bin}/gmcat version"
  end
end
