# This file was generated by GoReleaser. DO NOT EDIT.
class Acert < Formula
  desc "Command-line utility for creating and managing X.509 identities"
  homepage "https://github.com/greymatter-io/acert"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greymatter-io/acert/releases/download/v0.2.0/acert_0.2.0_darwin_x86_64.tar.gz"
    sha256 "6e4910edee84a427278af3ca8807a7580d3252bfe1ab79940c98013537e43d95"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/greymatter-io/acert/releases/download/v0.2.0/acert_0.2.0_linux_x86_64.tar.gz"
      sha256 "0610217050f81afad53bc01e50784d13446a3cdf1320f7b34dcf58f4fdd05304"
    end
  end

  def install
    bin.install "acert"
  end

  test do
    system "#{bin}/acert version"
  end
end
