# This file was generated by GoReleaser. DO NOT EDIT.
class Acert < Formula
  desc "Command-line utility for creating and managing X.509 identities"
  homepage "https://github.com/greymatter-io/acert"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greymatter-io/acert/releases/download/v0.2.1/acert_0.2.1_darwin_x86_64.tar.gz"
    sha256 "4c655987ca87142da72333c8ed8bd6811b0dd9c310cdc359ec0f1ea5bdead424"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/greymatter-io/acert/releases/download/v0.2.1/acert_0.2.1_linux_x86_64.tar.gz"
      sha256 "827a9810c669b78f6b199e8dbb404e2d62af3573d8e46d277bec1bdfaccc82ee"
    end
  end

  def install
    bin.install "acert"
  end

  test do
    system "#{bin}/acert version"
  end
end
