# This file was generated by GoReleaser. DO NOT EDIT.
class Gmcat < Formula
  desc "GmCat is a tool to interact with The GreyMatter Service Mesh's Catalog"
  homepage "https://github.com/greymatter-io/gmcat"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greymatter-io/gmcat/releases/download/v0.0.9/gmcat_0.0.9_darwin_amd64.tar.gz"
    sha256 "79d3e90e7d24a410a083b25ef90a613ad3a550f69a45e20c5a784243467d15d4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/greymatter-io/gmcat/releases/download/v0.0.9/gmcat_0.0.9_linux_amd64.tar.gz"
      sha256 "715cf972a651258f070130af1536ae760fb8d7dc0a58858ae619614aa903b092"
    end
  end

  def install
    bin.install "gmcat"
  end

  test do
    system "#{bin}/gmcat version"
  end
end
