# This file was generated by GoReleaser. DO NOT EDIT.
class Gmcat < Formula
  desc "GmCat is a tool to interact with The GreyMatter Service Mesh's Catalog"
  homepage "https://github.com/greymatter-io/gmcat"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greymatter-io/gmcat/releases/download/v0.0.7/gmcat_0.0.7_darwin_amd64.tar.gz"
    sha256 "75f5b52d535700f0ae9aa37bae33c7b82f0c049af9b14b1ae4822e23ec00cc95"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/greymatter-io/gmcat/releases/download/v0.0.7/gmcat_0.0.7_linux_amd64.tar.gz"
      sha256 "db00efc4d39a3bb11ea5c310c25dadf3c81bf2f8062cd7d10eda3d89e1434e7d"
    end
  end

  def install
    bin.install "gmcat"
  end

  test do
    system "#{bin}/gmcat version"
  end
end
