# This file was generated by GoReleaser. DO NOT EDIT.
class Incert < Formula
  desc "Ephemeral certificate authority"
  homepage "https://github.com/greymatter-io/incert"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greymatter-io/incert/releases/download/v0.1.0/incert_0.1.0_darwin_x86_64.tar.gz"
    sha256 "f9f83a6e44a40452d358cc476b5b91287b5aa5b0eaa6f46f30540d206b76c5e1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/greymatter-io/incert/releases/download/v0.1.0/incert_0.1.0_linux_x86_64.tar.gz"
      sha256 "663c19f7b95704172f779ddb0ba2dbff9ab805e09ef9249c81fd0e183a8959d8"
    end
  end

  def install
    bin.install "incert"
  end

  test do
    system "#{bin}/incert version"
  end
end
